spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monuments
    username: admin
    password: admin
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    properties:
       javax:
         persistance:
           schema-generation:
             create-source: metadata
             scripts:
               action: create
               create-target: db_create.sql
